version: '1.0'
name: pipeline-20220215
displayName: vite-note
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-f0d34dfa
    displayName: 打包
    strategy: naturally
    trigger: auto
    executor:
      - hnys
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - git remote rm origin
          - git remote add origin https://gitee.com/hnys/vite-note.git
          - git remote -v
          - npm ci
          - npm run build -- --gitee
          - git add .
          - git commit -m 'update'
          - git push --set-upstream origin master
permissions:
  - role: admin
    members: []
